Preparando base de dados

In [23]:
import pandas as pd
#importando arquivos
vendas_df = pd.read_csv('Contoso - Vendas - 2017.csv', sep=';')
produtos_df = pd.read_csv('Contoso - Cadastro Produtos.csv', sep=';')
lojas_df = pd.read_csv('Contoso - Lojas.csv', sep=';')
clientes_df = pd.read_csv('Contoso - Clientes.csv', sep=';')

#limpando apenas para colunas que queremos

clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Categoria']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

#mesclando e renomeando dataframes

vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
vendas_df = vendas_df.merge(clientes_df, on= 'ID Cliente').rename(columns={'E-mail':'E-mail Cliente'})
display(vendas_df)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Categoria,Nome da Loja,E-mail Cliente
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,Câmera Digital,Loja Contoso Austin,rbrumfieldmy@ameblo.jp
1,2,01/01/2017,06/01/2017,5,308,1586,2,18469,9,1,Filme DVD,Loja Contoso North America Reseller,cshawd4@technorati.com
2,3,01/01/2017,01/01/2017,0,294,1444,5,19730,13,1,Smartphone,Loja Contoso Tehran No.2,kgorriekd@bandcamp.com
3,4,01/01/2017,01/01/2017,0,251,1468,5,29326,6,1,Smartphone,Loja Contoso Singapore,angela49@adventure-works.com
4,5,01/01/2017,07/01/2017,6,94,1106,2,22617,4,1,Câmera Digital SLR,Loja Contoso Grand Prairie,jacob4@adventure-works.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,980638,31/12/2017,31/12/2017,0,194,2490,4,10353,120,0,Acessórios para Telefone & Tablet,Loja Contoso Ridgely,ocrosson9u@illinois.edu
980638,980639,31/12/2017,06/01/2018,6,32,2488,4,31750,120,0,Acessórios para Telefone & Tablet,Loja Contoso Milliken,victor11@adventure-works.com
980639,980640,31/12/2017,03/01/2018,3,210,2511,10,12003,80,0,Acessórios para Telefone & Tablet,Loja Contoso Cheshire,mtopaz4@gmpg.org
980640,980641,31/12/2017,31/12/2017,0,53,436,4,25550,39,0,Desktop,Loja Contoso East Troy,lance5@adventure-works.com
980641,980642,31/12/2017,31/12/2017,0,309,2510,10,28707,80,0,Acessórios para Telefone & Tablet,Loja Contoso Europe Reseller,jan8@adventure-works.com

Qual o % das vendas que foi devolvido?(Total devolvido/ Total Vendido
)

In [24]:
qnt_vendida = vendas_df['Quantidade Vendida'].sum()
qnt_devolvida = vendas_df['Quantidade Devolvida'].sum()

print('{:.2%}'.format(qnt_devolvida / qnt_vendida))

1.17%

Agora, se quisermos fazer a mesma análise apenas para 1 loja. Queremos filtrar apenas os itens da Loja Europe Online e saber % de devolução dessa loja.

In [31]:
so_loja_europe = vendas_df[vendas_df['ID Loja'] == 306]
#display(so_loja_europe)
qnt_vendida_europe = so_loja_europe['Quantidade Vendida'].sum()
qnt_devolvida_europe = so_loja_europe['Quantidade Devolvida'].sum()

print('{:.2%}'.format(qnt_devolvida_europe/qnt_vendida_europe))

1.33%

Se eu quisesse criar uma tabela apenas com as vendas Contoso Europe Online e que nao teveram nenhuma devolução. Quero criar essa tabela e saber quantas vendas são.

In [34]:
so_loja_europe_sem_devolucao = vendas_df[(vendas_df['ID Loja']==306) & (vendas_df['Quantidade Devolvida']==0)]
display(so_loja_europe_sem_devolucao)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Categoria,Nome da Loja,E-mail Cliente
98,99,01/01/2017,03/01/2017,2,306,1269,10,26238,8,0,Acessório para Câmera,Loja Contoso Europe Online,edward17@adventure-works.com
165,166,01/01/2017,02/01/2017,1,306,1107,10,7242,16,0,Câmera Digital SLR,Loja Contoso Europe Online,khanhard6r@taobao.com
166,167,01/01/2017,05/01/2017,4,306,242,10,34277,16,0,Home Theater,Loja Contoso Europe Online,marshall24@adventure-works.com
186,187,01/01/2017,06/01/2017,5,306,1479,10,23132,8,0,Tablet,Loja Contoso Europe Online,cynthia4@adventure-works.com
198,199,01/01/2017,03/01/2017,2,306,819,10,5363,4,0,Acessório para Computador,Loja Contoso Europe Online,svirgoea4@blogtalkradio.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980579,980580,31/12/2017,06/01/2018,6,306,771,10,6539,8,0,Acessório para Computador,Loja Contoso Europe Online,hgauntleyf0@smh.com.au
980580,980581,31/12/2017,01/01/2018,1,306,591,10,32061,8,0,Projetor,Loja Contoso Europe Online,gina18@adventure-works.com
980581,980582,31/12/2017,31/12/2017,0,306,1388,10,22838,8,0,Telefone para Casa & Escritório,Loja Contoso Europe Online,alexa14@adventure-works.com
980582,980583,31/12/2017,03/01/2018,3,306,1354,10,33450,8,0,Telefone para Casa & Escritório,Loja Contoso Europe Online,alexis3@adventure-works.com
980632,980633,31/12/2017,31/12/2017,0,306,1086,10,12240,4,0,Câmera Digital SLR,Loja Contoso Europe Online,gtabert6p@friendfeed.com

Desafio: e se eu quisesse criar uma tabela apenas com as vendas de Loja Contoso Europe Online e que não tiveram nenhuma devolução. Quero criar essa tabela e saber quantas vendas são.